### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by foolskill** [raindropdevs/RaindropSonataThemeBundle#4]
Hi Team,
I just installed your bundle and I absolutely follow your documentation but I can not get a result on my SonataAdminBudle.

Is there another configuration to change the theme of my admin

My configuration:

```
raindrop_sonata_theme:
    theme: yeti
```

I would like to change the theme of my admin with your bundle

Thank's a lot

**Comment by matteocaberlotto** [comment]
Hello,
which version of symfony and sonata did you try?
